### GET Request
GET https://virgil-backend.camps.fahrul.id/admin/categories
Content-Type: application/json

### GET Request by id
GET https://virgil-backend.camps.fahrul.id/admin/categories/1

Content-Type: application/json

### POST Request login
POST https://virgil-backend.camps.fahrul.id/auth/login
Content-Type: application/json

{
  "email": "baru@gmail.com"
}


### POST Request forgot password
POST https://virgil-backend.camps.fahrul.id/auth/forgot-password
Content-Type: application/json

{
  "email": "baru@gmail.com"
}

### POST Request reset password
PATCH  https://virgil-backend.camps.fahrul.id/auth/reset-password
Content-Type: application/json

{
  "code-otp": "322733",
  "email": "baru@gmail.com",
   "new_password": "newpassword123"
}